### ISSUE TITLE
terminal double-quotes in a multiline string must be escaped

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#296]
The following must be retained: `"""\""""`, but currently the escaped double-quote is unescaped, which makes an invalid output.

**Comment by avh4** [comment]
Fixed in b91de6ce...95d598ac

**Comment by AntouanK** [comment]
@avh4 Is this fixed?

Can you try to click "format" on this one? https://ellie-app.com/W8jbBNmYwra1/0
I have a similar problem in my code, where it removes escaped quotes on save.

**Comment by avh4** [comment]
With elm-format-0.6.1-alpha, your example code formats as

```elm
module Main exposing (..)

import Html exposing (Html, text)


main : Html a
main =
    let
        world =
            "World"

        content =
            """Hello
    there \"""" ++ world ++ """"
    !"""
    in
        text content
```

which keeps the `\"` after "there".

So it looks like ellie-app is not yet using the latest elm-format.

**Comment by AntouanK** [comment]
I get the same on atom with the `elm-format` plugin. I posted the ellie link as an example.
Seems like I have `0.5.2-alpha` so I have to update as well.
Thanks.

**Comment by AntouanK** [comment]
Seems like I still have a problem.
I got the latest version, 0.6.1, and I have this code
```elm
"""id: \"""" ++ listId ++ """\","""
```
after saving becomes
```elm
"""id: \"""" ++ listId ++ """","""
```

**Comment by avh4** [comment]
That's intended behavior.  Double quotes at the beginning of multiline strings do not need to be escaped  unless there are at least three of them, and elm-format removes the unnecessary backslashes.

**Comment by AntouanK** [comment]
Oh, I learned something. Thanks.
